# .github/workflows/tests.yml
name: Continuous Integration

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: write

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Lint with mypy
        run: |
          mypy ppModule --check-untyped-defs
          mypy unitTests
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt-get install libglu1
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Run tests
        run: |
          set -o pipefail
          pytest  -m pytest --cov=ppModule unitTests/ 2>&1 | tee coverage.txt
