# .github/workflows/tests.yml
name: Continuous Integration

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install mypy
        run: |
          pip install numpy
          pip install pytest
          python -m pip install --upgrade pip
          pip install mypy
      - name: Lint with mypy
        run: |
          mypy ppModule --check-untyped-defs
          mypy unitTests
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt-get install libglu1
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov pytest-mock
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -o pipefail
          python  -m pytest --cov=ppModule -v unitTests/ 2>&1 | tee coverage.txt
      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.txt
          retention-days: 1
